### ISSUE TITLE
use std::clamp :)

### ISSUE THREAD

**Issue by szborows** [Mrokkk/termite#1]
never heard of it?
http://en.cppreference.com/w/cpp/algorithm/clamp

**Comment by Mrokkk** [comment]
Yup, I didn't know this is going to be introduced in C++17. Otherwise, it was a part of original repo of termite, so I've just leave it ;) But now I'm going to replace it with std::clamp

**Comment by Mrokkk** [comment]
However, it's covered neither in GCC nor in Clang library implementation yet.
